### ISSUE TITLE
We want a "Partners" page that looks like Luminate's

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#79]
see https://luminategroup.com/portfolio.

- [ ] Create a new page type for Partners (start with the fields in the above example)
- [ ] Create a new index page for Partners that lists them all (style in the example above)
- [ ] Add filtering capability
- [ ] Add search capability

**Comment by scott-psycle** [comment]
@danblah We'll start to have a look at spec'ing the details for this new page type.  A couple of initial questions though.

1. Am I correct that you want to have a list page for ALL investments and also an individual Partner page type which gives details of a specific partner organisation, similar to this on Luminate?  https://luminategroup.com/investee/africa-check

2. On Luminate we have a couple of entities:

* Investment
* Organisation (Partner)

An Organisation can have multiple investments associated with it.  Will this be the case with Reset?  Or will it be 1:1?

I'll come back to you to confirm specifics about data fields and values once we've had a chance to discuss.

**Comment by danblah** [comment]
1. Yes.
2. Yes. 

Exactly.

**Comment by danblah** [comment]
Also not for MVP but so we don't make it in a way that makes it not possible... Along with the ability to manually create organizations and add projects/investments to them, we're going to want the ability to create a new project/investment from approved applications (or associate a new application to an existing organization as a new investment) in an automated way.

**Comment by danblah** [comment]
Bump bump on this. Can we get an update and some progress here?

**Comment by Parbhat** [comment]
@danblah Is this issue ready to work on? If yes and no one is working on it, @ankitjavalkar can start work on it.

**Comment by frjo** [comment]
@Parbhat Yes, this is ready to work on.

**Comment by Parbhat** [comment]
Thanks @frjo. @ankitjavalkar You can go through the issue and ask questions if need more details in requirements.

**Comment by frjo** [comment]
@Parbhat @sks444 Some parts of this might be time-consuming. Reset would not mind a simpler version with the basic functionality as a start. Extra features can then be added in future work.

The two content types with a minimum set of fields and a table view is a good start. Maybe possible to reuse part from "/apply/submissions/all/" able view?

**Comment by sks444** [comment]
Thanks for the updates @frjo. I will look into the table implementations done for `/apply/submissions/all/` and try to use the same for this feature.

**Comment by sks444** [comment]
@frjo, wanted to confirm a few things before proceeding with the implementations:

- [ ] We need to create two entities `Organization`(partner) and `Investment`. (One organization can have many investments)

- [ ] For the initial version as in MVP, these entities will be manually created from the admin portal.

- By looking at the Luminate's data I have come up with following fields for the initial version, let me know if there is more to be added:

```
Organization:
    - name 
    - status: current partner, alumni partner
    - type: profit, non-profit
    - description: a small description about the partner
    - logo-url: partner logo
    - web-url: website url of the partner

Investment:
    - name
    - primary impact area: a choice field with choices(Civic Empowerment, Data & Digital Rights, Financial Transparency, Independent Media, Reset, Other)
    - geographic focus: a choice field with choices(Africa, Central & Eastern Europe, Global, Latin America, Multi-Country, Southeast Asia, United States, Western Europe, other)
    - year
    - amount committed(in USD)
    - type
    - purpose
    - description
```

- [ ] Should the fields `primary impact area` and `geographic focus` be at Organization level or having them at Investment level is okay? 

- [ ] Should the fields `primary impact area` and `geographic focus` be a text input field or a choice field with above given choices is okay?

- [ ]  Should the field investment `type` be a choice field or a text input field. If choice, what could be the choices? Luminate's have values like, `Grant: Foreign Public Charity Equivalent`, `Capital Budget` etc.

- [ ] Should the field investment `purpose` be a choice field or a text input field. If choice, what could be the choices? Luminate's have values like, `General Funding Grant`, `Project Grant`, `Program Grant`, etc.

**Comment by frjo** [comment]
@danblah Can you answer the questions above?

**Comment by sks444** [comment]
@frjo, setting up the this repo for the first time, while I know that the setup and everything is very similar to hypha. 

When I run the server locally it still gives me sites configured for Open Technology Fund(E.g. Homepage etc.)

Is there some configuration that we need to do to have the sites configured with reset interface locally?

Also, please let me know if there is a db dump that you have specific to this repo.

Or if there is a document on doing specific setup for reset.

**Comment by frjo** [comment]
@sks444  Reset has custom models for front page etc. Will get you a sanitised db dump from Reset test, that will be the quickest and easiest I think.

**Comment by sks444** [comment]
Yes, that will do the work. Thank you.

**Comment by danblah** [comment]
@sks444 and @frjo, responding.

- [ ] We need to create two entities `Organization`(partner) and `Investment`. (One organization can have many investments)

**Yes, let us call it partner.**

- [ ] For the initial version as in MVP, these entities will be manually created from the admin portal.

**Yes, that's right.**

- By looking at the Luminate's data I have come up with following fields for the initial version, let me know if there is more to be added:

**I've modified below.**


```
Partner ~~Organization~~:
    - name*
    - status: active, inactive* ~~current partner, alumni partner~~
    - public: yes/no* 
    - description: a small description about the partner
    - logo-url: partner logo
    - web-url: website url of the partner
    - Option to include and require one or more Category Question, for example:
    -- type: Can we use the Category Question "[Organization Type](https://apply.reset.tech/admin/categories/category/edit/1/)"? ~~profit, non-profit, individual~~

Investment:
    - name*
    - year*
    - amount committed (in USD)*
    - description*
    - application: select from any approved application
    - Option to include and require one or more Category Question, for example:
    -- type of work: Can we use the Category Question "[Type of Work](https://apply.reset.tech/admin/categories/category/edit/5/)"? ~~primary impact area: a choice field with choices(Civic Empowerment, Data & Digital Rights, Financial Transparency, Independent Media, Reset, Other)~~
    -- region: Can we use Category Question "[Region]([url](https://apply.reset.tech/admin/categories/category/edit/4/))"? ~~geographic focus: a choice field with choices(Africa, Central & Eastern Europe, Global, Latin America, Multi-Country, Southeast Asia, United States, Western Europe, other)~~

* indicates required

```

- [ ] Should the fields `primary impact area` and `geographic focus` be at Organization level or having them at Investment level is okay? 

**Investment level is right and okay. This assumes we would easily be able to search/filter/find organisations by fields of the investments associated with them.** 

- [ ] Should the fields `primary impact area` and `geographic focus` be a text input field or a choice field with above given choices is okay?

**They should be replaced by choosing a Category Question.**

- [ ]  Should the field investment `type` be a choice field or a text input field. If choice, what could be the choices? Luminate's have values like, `Grant: Foreign Public Charity Equivalent`, `Capital Budget` etc.

**They should be replaced by choosing a Category Question.**


- [ ] Should the field investment `purpose` be a choice field or a text input field. If choice, what could be the choices? Luminate's have values like, `General Funding Grant`, `Project Grant`, `Program Grant`, etc.

**They should be replaced by choosing a Category Question.**
